### ISSUE TITLE
The build is setup for 2015_2016

### ISSUE THREAD

**Issue by keprt** [NIVeriStandAdd-Ons/SLSC-12201-DIO-Plugin-Custom-Device#2] opened 2017-11-02 08:30 UTC
The symbols for build are setup for 2015_2016. Should be 2017 by default.
~Jiri

**Comment by Alexbarp** [comment] 2018-07-03 20:15
I changed the comments to tell what the customer has to do to build in specific version in the Readme. Is this OK for you now or you still think we should change the default to VS2017 and further (which is actually "Default"

**Comment by jashnani** [comment] 2019-04-05 19:12
I'm not migrating this issue to the [new location of this custom device](https://github.com/ni/niveristand-slsc-12201-custom-device) as it is not applicable. We have a different build setup in the new repo.

**Comment by Alexbarp** [comment] 2019-04-05 19:38
@jashnani , but I would advise to do what Jiri suggested though. We should make the project to have the symbol as "default", because then, if you get the CD in the "latest" version of VS and have to build it manually (when you really would need it because we don't have an official version), then, you would not need to bother with that. The "2015_2016" is the special case and we should keep that around while we support those versions.

**Comment by jashnani** [comment] 2019-04-05 20:54
@Alexbarp it looks like we're already doing that here: https://github.com/ni/niveristand-slsc-12201-custom-device/blob/master/build.toml

**Comment by Alexbarp** [comment] 2019-04-05 21:10
Again, what I am saying don't have to do with the build process. Basically the issue is: IF a SE/AE get the code (probably in VS 2019) and try to **build manually** that code, he has to change the symbol because it is set to "2015_2016". If we have the symbol project set to "default", then they don't need to do it. That will save work and my suggestion is to do that. This would be better than keeping "2015_2016".

**Comment by jashnani** [comment] 2019-04-05 21:35
I don't think **building custom devices manually** is a use case we're prioritizing for officially supported custom devices. In most cases, when a new VeriStand version is released, we plan on building and releasing officially supported custom devices alongside it.

**Comment by buckd** [comment] 2019-04-08 12:23
@jashnani We should change this. It's basically no work at all and will make life easier once we don't support the older versions anymore.

**Comment by Alexbarp** [comment] 2019-04-08 18:05
So, do we agree that we should just change the symbol to "Default" using LabVIEW 2015 for now? If yes, then I can close this issue here too.

**Comment by jashnani** [comment] 2019-04-09 20:27
Yes, I agree with should change the lvproject symbol to default. Based on my conversation with @buckd this is a very easy fix that will help anyone trying to build manually. @buckd plans on putting a pull request soon, so I won't bother opening an issue.

**Comment by Alexbarp** [comment] 2019-04-09 20:32
Closing this issue here. For this depot, we decided not to change right now and if you want the latest version with this change, go to [https://github.com/ni/niveristand-slsc-12201-custom-device](https://github.com/ni/niveristand-slsc-12201-custom-device)

**Closed as completed by Alexbarp** 2019-04-09 20:32 UTC
